### ISSUE TITLE
Add grower image upload endpoint

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-api#111]
Admin Panel users need to be able to upload better images of their growers for display on the Admin Panel and the Web Map.
See Greenstand/treetracker-admin-client#192.

**Comment by krisblarq** [comment]
I would like to work on this issue!

**Comment by Kpoke** [comment]
Awesome @krisblarq, let me know if you have any questions concerning the implementation. I would assign this task to you and also add you to the microservices channel on slack

**Comment by gustarpd** [comment]
is this endpoint done?

**Comment by krisblarq** [comment]
No it’s not, a ran into a bit of a road block. Implemented the endpoint,
but when I test, I get an error “application only accepts app/json”. Still
trying to figure it out.

**Comment by Kpoke** [comment]
You could do something like this in the app.js file, that should fix the issue
![image](https://user-images.githubusercontent.com/28721558/199972984-cca4a8ae-12c5-457a-a623-05351ece9e72.png)
