### ISSUE TITLE
Change the planting_organization_id to uuid and  allow `null`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-api#122]
https://github.com/Greenstand/treetracker-api/blob/47bb0af8179bf513a19737145447b3fa0746ba17/database/migrations/sqls/20210218195106-capture-up.sql#L16

**Comment by dadiorchen** [comment]
@Kpoke is this what we decided, right?

**Comment by Kpoke** [comment]
Yeah, it has already been changed to uuid though, leaving just the nullable migration

**Comment by Kpoke** [comment]
#127
