### ISSUE TITLE
Review Service Code

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-api#25]
Perform a review of the development state of this service, including the following tasks

Update to node 16, test for compatibility, fix compatibility issues

Check CI/CD - installed and working?
* test, release, deploy automation for dev environment
* test when a new PR is submitted
* Manual deployment to testing environment

Fix linting errors if present
* Run linter and fix errors
* Fix linter warnings: npm run lint
** npm run lint:fix will fix some things automatically

Review state of testing 
* Do unit tests exist
* Do integration test exist
* Do tests run successfully
* Is test running straightforward
* Review test coverage

Review state of open PRs
* Can they be merged
* Resolve conflicts

Review state of open issues
* Resolve any simple issues
* Ask questions about unclear or complex issues

Microservices implementation structural review
* Is our software architecture approach to microservices implementation working well for this project

**Comment by yefenny** [comment]
I am trying to push to the repository and I can't.
