### ISSUE TITLE
Finish potential_matches endpoint

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-api#26]
The endpoint /trees/potential_matches?capture_id=<uuid of the capture> returns trees that could potentially be the tree represented in the given capture (using location criteria).  This endpoint was implemented using an ad hoc architecture, and needs to be ported into the functional domain model used by the rest of the code.

Existing SQL for this endpoint is in the routes-old directly of the branch 'potential-matches' in this repository.  I have done a little bit of the work for setting up the handler as well (treeHandler.js)

Please complete the port, and implement a few tests to test the functionality.

**Comment by gwynndp** [comment]
@ZavenArra May have been closed by https://github.com/Greenstand/treetracker-api/pull/36
