### ISSUE TITLE
Fix markdown grammar disorder in readme

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-api#27]
![image](https://user-images.githubusercontent.com/5744708/139030294-5a01f130-aa21-4589-9f94-dadc2e1e9f51.png)

**Comment by krisblarq** [comment]
Hi, @dadiorchen can you shed more light on what needs to be done here?

**Comment by nmcharlton** [comment]
@krisblarq Looks like the code blocks and plain text are the wrong way round.
We're missing a ` ``` ` somewhere.

**Comment by shaikhahmed243** [comment]
Hi @nmcharlton if this issue is not closed can I fix this?

**Comment by nmcharlton** [comment]
@dadiorchen Can you assign this to @LoftyDroid?

**Comment by johny4437** [comment]
Was this assign to someone? I would like to help with this.

**Comment by Kpoke** [comment]
The readme is also massively out of date and should be based on https://github.com/Greenstand/treetracker-microservice-template/blob/main/README.md

**Comment by Kpoke** [comment]
@johny4437 still interested in this issue?

**Comment by pranavkparti** [comment]
This issue is resolved and should be closed.
