### ISSUE TITLE
Create the endpoint that creates resource named Capture

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-api#5]
Create a http POST end point that creates resource named Capture.

The request specification is available in the following [api doc](https://github.com/Greenstand/treetracker-api/blob/master/docs/api/spec/treetracker.v1.yaml).

NOTE: Please use a tool named https://stoplight.io/ to view the specification. It is more readable than the yaml file. Let me know if anything here isn't clear.

**Comment by mtwn105** [comment]
Hi @arunbakt I would like to try this one

**Comment by arunbakt** [comment]
Hi @mtwn105 , thank you for your interest in contributing. Could you sign up here (https://greenstand.org/contribute) so that we can connect and have an introduction ?

**Comment by mtwn105** [comment]
Hi @arunbakt I have filled up the Google form

**Comment by arunbakt** [comment]
Hi @mtwn105 , I have sent a slack and github invite to you. Lets connect and ensure no one else is working on this issue and you can take it.
