### ISSUE TITLE
Create a `GET` end point for resource named `tree` with path `/trees`

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-api#8]
Create a `GET` end point for resource named `tree` with path `/trees`. The api should support pagination with `limit` and `offset` query parameters. Additional filtering criteria is not known at this point and to be added later.

The request specification is available in the following api doc.

https://github.com/Greenstand/treetracker-api/blob/master/docs/api/spec/treetracker.v1.yaml

Note: Please use a tool named https://stoplight.io/ to view the specification. It is more readable than the yaml file. Let me know if anything here isn't clear.

**Comment by AnitaNa** [comment]
@arunbakt, Do I have to create a new workspace for a stoplight, or is there already an existing workspace for greensand which we need to use?

**Comment by AnitaNa** [comment]
@arunbakt, which API doc have you refer to in this line "The request specification is available in the following api doc."

**Comment by arunbakt** [comment]
@AnitaNa, updated the issue with the link to the api doc.
