### ISSUE TITLE
Tags need an owner ID

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-api#83]
Tags (entries in the `tag` table) need to be owned by the organization that created them to ensure one org's tags do not appear in the Tag filter and autocomplete for another org.

See https://github.com/Greenstand/treetracker-admin-client/issues/620 for the corresponding Admin Panel issue.

**Comment by Kpoke** [comment]
Currently, there is a unique constraint on tag names, is that fine or should the unique constraint be the name and owner_id? @nmcharlton

**Comment by nmcharlton** [comment]
@Kpoke The unique constraint should be on owner_id and name. Owners must be able to duplicate names already used by other owners.
